### PR TITLE
Made some changes from the test repo

### PR DESCRIPTION
**Pull request by Bryn21**
Merge branch into master.

### CODE REVIEW

**Comment by Bryn21** [comment]
Merge from branch to master

**Comment by Carringguns** [comment]
I wont take ur work. Nice job

**Comment by Bryn21** [comment]
lol, why did you comment here? haha I'm just committing random stuff to learn how to use it. Thanks for the motivational vote of confidence :-)

**Comment by Carringguns** [comment]
Same here but stuck aaarg

**Comment by Bryn21** [comment]
I used a mixture of these two:
Guide using just github: https://guides.github.com/activities/hello-world/
Guide using Visual Studio: http://michaelcrump.net/setting-up-github-to-work-with-visual-studio-2013-step-by-step/
Hope it helps :-)

**Comment by Carringguns** [comment]
Ill see if I can help you with some team help. They hooked me up

**Comment by Bryn21** [comment]
I'm OK thanks, I don't need any help. It's also work for a university assignment so I can't have help anyway :-) Ill let you know if I get stuck with anything

**Pull request merged**
